import pieIconPNG from './pie.png';
import pieFocusedIconPNG from './pie-focused.png';
import pieDisabledIconPNG from './pie-disabled.png';
import chartIconPNG from './chart.png';
import chartFocusedIconPNG from './chart-focused.png';
import currencyIconPNG from './currency.png';
import currencyFocusedIconPNG from './currency-focused.png';
import magnifierIconPNG from './magnifier.png';
import magnifierFocusedIconPNG from './magnifier-focused.png';
import bellIconPNG from './bell.png';
import bellFocusedIconPNG from './bell-focused.png';
import userIconPNG from './user.png';
import userFocusedIconPNG from './user-focused.png';
import userWhiteIconPNG from './user-white.png';
import capIconPNG from './cap.png';
import arrowUpwardIconPNG from './arrow-upward.png';
import arrowDownwardIconPNG from './arrow-downward.png';
import amazonIconPNG from './amazon.png';
import appleIconPNG from './apple.png';
import googleIconPNG from './google.png';
import shopifyIconPNG from './shopify.png';
import teslaIconPNG from './tesla.png';
import verticalFilterIconPNG from './vertical-filter.png';
import verticalFilterFocusedIconPNG from './vertical-filter-focused.png';
import horizontalFilterIconPNG from './horizontal-filter.png';
import horizontalFilterFocusedIconPNG from './horizontal-filter-focused.png';

export const pieIcon: string = pieIconPNG;
export const pieFocusedIcon: string = pieFocusedIconPNG;
export const pieDisabledIcon: string = pieDisabledIconPNG;
export const chartIcon: string = chartIconPNG;
export const chartFocusedIcon: string = chartFocusedIconPNG;
export const currencyIcon: string = currencyIconPNG;
export const currencyFocusedIcon: string = currencyFocusedIconPNG;
export const magnifierIcon: string = magnifierIconPNG;
export const magnifierFocusedIcon: string = magnifierFocusedIconPNG;
export const bellIcon: string = bellIconPNG;
export const bellFocusedIcon: string = bellFocusedIconPNG;
export const userIcon: string = userIconPNG;
export const userFocusedIcon: string = userFocusedIconPNG;
export const userWhiteIcon: string = userWhiteIconPNG;
export const capIcon: string = capIconPNG;
export const arrowUpwardIcon: string = arrowUpwardIconPNG;
export const arrowDownwardIcon: string = arrowDownwardIconPNG;
export const amazonIcon: string = amazonIconPNG;
export const appleIcon: string = appleIconPNG;
export const googleIcon: string = googleIconPNG;
export const shopifyIcon: string = shopifyIconPNG;
export const teslaIcon: string = teslaIconPNG;
export const verticalFilterIcon: string = verticalFilterIconPNG;
export const verticalFilterFocusedIcon: string = verticalFilterFocusedIconPNG;
export const horizontalFilterIcon: string = horizontalFilterIconPNG;
export const horizontalFilterFocusedIcon: string =
  horizontalFilterFocusedIconPNG;
