import pieIconPNG from './pie.png';
import pieFocusedIconPNG from './pie-focused.png';
import pieDisabledIconPNG from './pie-disabled.png';
import chartIconPNG from './chart.png';
import chartFocusedIconPNG from './chart-focused.png';
import currencyIconPNG from './currency.png';
import currencyFocusedIconPNG from './currency-focused.png';
import magnifierIconPNG from './magnifier.png';
import magnifierFocusedIconPNG from './magnifier-focused.png';
import bellIconPNG from './bell.png';
import bellFocusedIconPNG from './bell-focused.png';
import userIconPNG from './user.png';
import userFocusedIconPNG from './user-focused.png';
import userWhiteIconPNG from './user-white.png';
import capIconPNG from './cap.png';
import arrowUpwardIconPNG from './arrow-upward.png';
import arrowDownwardIconPNG from './arrow-downward.png';
import amazonIconPNG from './amazon.png';
import appleIconPNG from './apple.png';
import googleIconPNG from './google.png';
import shopifyIconPNG from './shopify.png';
import teslaIconPNG from './tesla.png';
import verticalFilterIconPNG from './vertical-filter.png';
import verticalFilterFocusedIconPNG from './vertical-filter-focused.png';
import horizontalFilterIconPNG from './horizontal-filter.png';
import horizontalFilterFocusedIconPNG from './horizontal-filter-focused.png';
import caratDownIconPNG from './carat-down.png';

export const pieIcon = pieIconPNG;
export const pieFocusedIcon = pieFocusedIconPNG;
export const pieDisabledIcon = pieDisabledIconPNG;
export const caratDownIcon = caratDownIconPNG;
export const chartIcon = chartIconPNG;
export const chartFocusedIcon = chartFocusedIconPNG;
export const currencyIcon = currencyIconPNG;
export const currencyFocusedIcon = currencyFocusedIconPNG;
export const magnifierIcon = magnifierIconPNG;
export const magnifierFocusedIcon = magnifierFocusedIconPNG;
export const bellIcon = bellIconPNG;
export const bellFocusedIcon = bellFocusedIconPNG;
export const userIcon = userIconPNG;
export const userFocusedIcon = userFocusedIconPNG;
export const userWhiteIcon = userWhiteIconPNG;
export const capIcon = capIconPNG;
export const arrowUpwardIcon = arrowUpwardIconPNG;
export const arrowDownwardIcon = arrowDownwardIconPNG;
export const amazonIcon = amazonIconPNG;
export const appleIcon = appleIconPNG;
export const googleIcon = googleIconPNG;
export const shopifyIcon = shopifyIconPNG;
export const teslaIcon = teslaIconPNG;
export const verticalFilterIcon = verticalFilterIconPNG;
export const verticalFilterFocusedIcon = verticalFilterFocusedIconPNG;
export const horizontalFilterIcon = horizontalFilterIconPNG;
export const horizontalFilterFocusedIcon = horizontalFilterFocusedIconPNG;
